[theme]
base = "light"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f7"
primaryColor = "#2e51a2"
textColor = "#1c1c1c"
font = "Maven Pro:https://fonts.googleapis.com/css2?family=Maven+Pro:wght@400..900&display=swap"
codeFont = "Fira Code:https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap"

[runner]
fastReruns = true